import dotenv from 'dotenv';
dotenv.config();

export const config = Object.freeze({
  port: Number(process.env.PORT) || 3001,
  nodeEnv: process.env.NODE_ENV || 'development',
  jwt: {
    secret: process.env.JWT_SECRET || 'change-me-in-production',
    expiresIn: process.env.JWT_EXPIRES_IN || '7d',
  },
  db: {
    url: process.env.DB_URL,
    authToken: process.env.DB_TOKEN,
  },
  cors: {
    allowedOrigins: process.env.ALLOWED_ORIGINS || '',
  },
  bcryptRounds: 10,
  bodyLimit: '5mb',
  cleanupIntervalMs: 5 * 60 * 1000,
  notificationRetentionDays: 90,
  rateLimit: {
    auth: { windowMs: 60_000, max: 10 },
    api: { windowMs: 60_000, max: 100 },
    write: { windowMs: 60_000, max: 30 },
    socketMessages: { windowMs: 30_000, max: 15 },
  },
  messageEditWindowMs: 15 * 60 * 1000,
  shutdownTimeoutMs: 10_000,
  limits: {
    messageHistoryDefault: 30,
    messageHistoryMax: 200,
    paginationDefault: 20,
    paginationMax: 100,
    notificationLimit: 50,
    reviewWordsLimit: 20,
    leaderboardLimit: 20,
    mentionsLimit: 50,
    emojiLimit: 30,
    auditLogLimit: 100,
    correctionsLimit: 30,
    searchMinLength: 2,
    searchDefaultLimit: 10,
    searchMaxLimit: 50,
    trendingWordsLimit: 30,
    trendingRecentMessages: 500,
    trendingMinWordLength: 4,
    quizXpPerCorrect: 5,
    helpfulCorrectionXp: 5,
    profileViewRetentionDays: 90,
    followersMax: 100,
    exportMessagesLimit: 1000,
    exportNotificationsLimit: 1000,
    bulkBanMax: 50,
    bulkDeleteMax: 100,
    bulkNotificationMax: 500,
    membershipDurationDays: 30,
    heatmapDays: 365,
    progressWeeks: 84,
    digestDays: 7,
  },
  cleanup: {
    interval: 5 * 60 * 1000,
    passwordResetExpiry: 60 * 60 * 1000,
  },
});
